include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
